In [5]:
import numpy as np
import matplotlib.pyplot as plt
import bilby

%matplotlib inline

In [6]:
def true_model(x):
    return (0.16 * x ** 2 - 4) * (0.04 * x ** 2 - 1)

def partial_model(x, a, b):
    return - a * x ** 2 + b

In [17]:
x_data = np.linspace(-10, 10, 13)
y_true = true_model(xs)

y_data = np.array(
    [
        np.random.normal(loc=mean, scale=0.05, size=3)
        for mean in y_true
    ]
)
y_data = np.array([y_data[:,n] for n in range(3)])

[[ 3.59803093e+01  3.59206082e+01  3.59803223e+01]
 [ 1.26641640e+01  1.27078822e+01  1.26336825e+01]
 [ 2.47296944e+00  2.46146495e+00  2.49364579e+00]
 [ 2.33160485e-02  6.64082938e-02  5.73008915e-02]
 [ 1.22517614e+00  1.33452969e+00  1.17693363e+00]
 [ 3.20065143e+00  3.15247707e+00  3.19966791e+00]
 [ 3.97297661e+00  4.01850558e+00  4.05694770e+00]
 [ 3.14347274e+00  3.12187844e+00  3.13802214e+00]
 [ 1.22448151e+00  1.27420654e+00  1.22633848e+00]
 [ 2.18964533e-02 -5.17233430e-02  6.04495640e-02]
 [ 2.48658712e+00  2.37272928e+00  2.46882448e+00]
 [ 1.26272823e+01  1.26450917e+01  1.26308332e+01]
 [ 3.60474288e+01  3.60117171e+01  3.59497056e+01]]
[[ 3.59803093e+01  1.26641640e+01  2.47296944e+00  2.33160485e-02
   1.22517614e+00  3.20065143e+00  3.97297661e+00  3.14347274e+00
   1.22448151e+00  2.18964533e-02  2.48658712e+00  1.26272823e+01
   3.60474288e+01]
 [ 3.59206082e+01  1.27078822e+01  2.46146495e+00  6.64082938e-02
   1.33452969e+00  3.15247707e+00  4.01850558e+00  3.